### PR TITLE
Adding npx configure react commands

### PR DESCRIPTION
**Pull request by shaantanu9**
## Change Summary

Added the `npx configure-react` commands that help setup react app faster

### Description
Added the npx configure-react commands that help setup react app faster
https://www.npmjs.com/package/configure-react

### Screenshots or Links

npx configure-react

### Additional context
This help any new developer to set the React App Faster and can start learning and implementing things easily

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice.**

### General

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md)
- [x] I've made some valid changes to the CheatSheet, and they are not just minor changes.

### Changes

- [x] I've read and followed the [Solution Template](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md#submission-template)

**Note: To mark the checkbox, put an `x` inside the `[ ]` (like this: `[x]`).**

### CODE REVIEW

**Comment by aryankashyap7** [comment]
@shaantanu9 Do correct me if I'm wrong!

Aren't all these commands related to ReactJs? You could have created a section in the react Cheatsheet and added them over there.

**Comment by Dhravya** [comment]
Yeah, these should be in react cheatsheet!!
Also side note: Please remove the "Back to Top" buttons, not needed anymore

**Comment by aryankashyap7** [comment]
You can even remove the `## Table of Contents` and `Back to top links`, because our deployed website, will now automatically detect the headings on the priority basis of hashtags.

**Comment by shaantanu9** [comment]
ok will do so, thanks

**Comment by shaantanu9** [comment]
@aryankashyap7  please check and let me know, what else needed or is it ok

**Pull request merged**
