### PR TITLE
CristinaEU1

### PR DESCRIPTION
**Pull request by CristinaEU1**
Added AWS cheatsheet

### CODE REVIEW

**Comment by aryankashyap7** [comment]
You need to add some more commands, that are used in the AWS consoles. Just 2 lines won't be accepted as a cheat sheet.

**Review by CristinaEU1 — COMMENTED** [review]
updated file

**Comment by CristinaEU1** [comment]
@aryankashyap7 have you checked the updated file?

**Comment by aryankashyap7** [comment]
@CristinaEU1 Yes, Now it looks good :)

**Pull request merged**
