### PR TITLE
Add spring boot annotations cheat sheet

### PR DESCRIPTION
**Pull request by shubhampandey18**
## Change Summary

Add spring boot annotations cheat sheet.

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice.**

### General

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md)
- [x] I've made some valid changes to the CheatSheet, and they are not just minor changes.

### Changes

- [x] I've read and followed the [Solution Template](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md#submission-template)

**Note: To mark the checkbox, put an `x` inside the `[ ]` (like this: `[x]`).**

### CODE REVIEW

**Comment by aryankashyap7** [comment]
Hi @shubhampandey18 Can you explain more about Spring Boot, It sure seems a new topic for me 🙂

**Comment by shubhampandey18** [comment]
Hey,
Spring Boot is a very popular Java Spring Framework for developing backend of web applications.
As it says here: https://www.ibm.com/cloud/learn/java-spring-boot

**Comment by shubhampandey18** [comment]
Spring Boot is a very popular framework among Backend/Full Stack developer community because it makes it easy to create stand-alone, production-grade Spring based Applications that you can "just run". It's also becoming very popular with the rise of microservice based architecture of applications because it best suited to create a micro service which you can "just run" any where wherever you can run java application.

Also do you mean I should add more about spring boot in the cheat sheet?

**Comment by aryankashyap7** [comment]
Yes, that would be really favorable, You can add a few more sections. Once those changes are made do ping me here. I would merge your PR with the tags :)

**Comment by shubhampandey18** [comment]
Hey @aryankashyap7 I have added some description of spring boot which will help for beginners in spring boot.
Please feel free to merge changes now with the tag.

**Comment by aryankashyap7** [comment]
This looks Good 🍁

**Pull request merged**
