### PR TITLE
Created an astro page to display all cheatsheets neatly

### PR DESCRIPTION
**Pull request by Dhravya**
## Change Summary

Created an astro app that displays everything in md format neatly #112 

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice.**

### General

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md)
- [x] I've made some valid changes to the CheatSheet, and they are not just minor changes.

### Changes

- [x] I've read and followed the [Solution Template](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md#submission-template)

**Note: To mark the checkbox, put an `x` inside the `[ ]` (like this: `[x]`).**

### CODE REVIEW

**Comment by Dhravya** [comment]
I've hosted a version here -> https://cheats.dhr.wtf/

I understand that this change is wayyy too big, so maybe we can shift it to another repo?

**Comment by aryankashyap7** [comment]
@Dhravya Do you use any other platform we can have a talk regarding this?

**Comment by Dhravya** [comment]
Discord, twitter, anything works

**Comment by aryankashyap7** [comment]
> Discord, twitter, anything works

Sure, I would be connecting via Twitter :)

**Comment by Dhravya** [comment]
@aryankashyap7 Conflicts fixed!

**Comment by aryankashyap7** [comment]
**Amazing Upgrade** 🍁

**Pull request merged**
