### PR TITLE
Added some tree commands to the Linux Cheat Sheet

### PR DESCRIPTION
**Pull request by Alfareiza**
## Change Summary

I'm adding the `tree` command to the Linux Cheat Sheets. Issue #150 

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice.**

### General

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md)
- [x] I've made some valid changes to the CheatSheet, and they are not just minor changes.

### Changes

- [x] I've read and followed the [Solution Template](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md#submission-template)

### CODE REVIEW

**Comment by aryankashyap7** [comment]
@Alfareiza There are some conflicts with your PR, resolve them.

**Comment by aryankashyap7** [comment]
There are some conflicts with your PR, resolve them.

**Comment by Alfareiza** [comment]
Could you give me a hand @aryankashyap7 I see on the logs messages something about build command error. Look at this 
`10:26:46 AM: npm ERR! code ENOENT
10:26:46 AM: npm ERR! syscall open
10:26:46 AM: npm ERR! path /opt/build/repo/package.json
10:26:46 AM: npm ERR! errno -2
10:26:46 AM: npm ERR! enoent ENOENT: no such file or directory, open '/opt/build/repo/package.json'
10:26:46 AM: npm ERR! enoent This is related to npm not being able to find a file.
10:26:46 AM: npm ERR! enoent
10:26:46 AM: npm ERR! A complete log of this run can be found in:
10:26:46 AM: npm ERR!     /opt/buildhome/.npm/_logs/2022-10-29T13_26_46_135Z-debug-0.log
10:26:46 AM: ​
10:26:46 AM: ────────────────────────────────────────────────────────────────
10:26:46 AM:   "build.command" failed                                        
10:26:46 AM: `

**Comment by aryankashyap7** [comment]
@Alfareiza You have tried building it over your local machine or these logs are from the netifly server?

**Comment by Alfareiza** [comment]
From Netlify server @aryankashyap7

**Comment by Dhravya** [comment]
These are merge conflicts, nothing wrong with the server. 
Git pull the main branch and resolve conflicts

**Pull request closed without merging**
