### PR TITLE
Fix stuff

### LINKED ISSUE #225: Vue.js commands error on cheats.dhr.wtf
Just me or the Vue commands look 'blank' on [https://cheats.dhr.wtf/sheet/vuejs/](https://cheats.dhr.wtf/sheet/vuejs/)?  `vuejs.md` file looks okay

How it looks like for me

image

### PR DESCRIPTION
**Pull request by nexxeln**
Closes #225 

## Change Summary

- Use shiki for syntax highliting
- Remove all ```text references cause it doesn't exist

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice.**

### General

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md)
- [x] I've made some valid changes to the CheatSheet, and they are not just minor changes.

### Changes

- [x] I've read and followed the [Solution Template](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md#submission-template)

Let me know if you want to change the theme, you can see the list of possible themes [here](https://github.com/shikijs/shiki/blob/main/docs/themes.md#all-themes)

### CODE REVIEW

**Comment by Dhravya** [comment]
Yep! Vue is fixed! Thanks nexxel :)

image

**Comment by nexxeln** [comment]
Also you might want to use html syntax highlighting in some places in the vue sheet because it doesn't highlight just divs or spans because it isn't valid vue syntax. It always has to be inside the template tag. I can add the html highlighting if you want

**Comment by Dhravya** [comment]
Yeah, makes sense. no issues, do it

**Comment by nexxeln** [comment]
> Yeah, makes sense. no issues, do it

Done

**Comment by aryankashyap7** [comment]
> > Yeah, makes sense. no issues, do it
> 
> Done

@nexxeln Looks Good 🍁

**Pull request merged**
