### PR TITLE
Add bash arguments in bash cheatsheet

### PR DESCRIPTION
**Pull request by shubhampandey18**
## Change Summary

Add section in bash cheat-sheet (Bash Arguments) for specifying arguments

## Checklist

**If you haven't fulfilled the below requirements or even delete the entire checklist, your PR won't be reviewed and will be closed without notice.**

### General

- [x] This Pull Request is all my own work. (You'll be blacklisted if you are caught for plagiarism.)
- [x] I've read [CONTRIBUTING.md](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md)
- [x] I've made some valid changes to the CheatSheet, and they are not just minor changes.

### Changes

- [x] I've read and followed the [Solution Template](https://github.com/aryankashyap7/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md#submission-template)

**Note: To mark the checkbox, put an `x` inside the `[ ]` (like this: `[x]`).**

### CODE REVIEW

**Comment by aryankashyap7** [comment]
These are some minor changes, so won't be acceptable for the tag.

**Comment by shubhampandey18** [comment]
Just curious @aryankashyap7 , is there any mention of the size of the contribution for it to be acceptable for the tag?

**Comment by aryankashyap7** [comment]
@shubhampandey18 Actually, according to my experience with hacktoberfest, I have noted that the repo that usually has minor changes is usually excluded. So to prevent any such mishappenings with other contributors it's better to have some major changes, i.e by adding a whole new cheat sheet, Modifying an entire section i.e > 150 lines, adding a new feature, resolving a bug, etc.

**Comment by shubhampandey18** [comment]
Okay, Thanks for explaining.
It helps.

**Pull request merged**
